services:
  mariadb:
    image: mysql:latest
    container_name: mysql_mobilia
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mobilia
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_mobilia
      environment: 
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: 1234
      restart: always
      ports:
        - 9011:80
volumes:
  mysql_data: