### Criar Contrato
POST http://localhost:8080/api/contrato
Content-Type: application/json

{
  "dataInicio": "2024-01-01",
  "dataFim": "2024-12-31",
  "dataVencimento": "2024-01-05",
  "valorDeposito": 1500.00,
  "objLocacao": "APARTAMENTO_RESIDENCIAL",
  "qtd": 1,
  "user": 1,
  "morador": 1
}

### Buscar Contrato por ID
GET http://localhost:8080/api/contrato/1

### Listar Todos os Contratos
GET http://localhost:8080/api/contrato

### Atualizar Contrato
PUT http://localhost:8080/api/contrato/1
Content-Type: application/json

{
  "id": 1,
  "dataInicio": "2024-01-01",
  "dataFim": "2024-12-31",
  "dataVencimento": "2024-01-05",
  "valorDeposito": 1600.00,
  "objLocacao": "APARTAMENTO_RESIDENCIAL",
  "qtd": 1,
  "user": 1,
  "morador": 1
}

### Download PDF do Contrato
GET http://localhost:8080/api/contrato/1/download

### Visualizar PDF do Contrato
GET http://localhost:8080/api/contrato/1/view

### Deletar Contrato
DELETE http://localhost:8080/api/contrato/1
